name: Publish patched code

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    name: Patch and publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        libcint_ref: ['v6.1.2']
    env:
      REF: 'latest'

    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
      - name: Set up clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
      - name: Install other dependencies
        run: |
          sudo apt-get -y install clisp meson ninja-build cmake
      - name: change ref (tag)
        if: contains(github.ref, 'tags')
        run: |
            echo "REF=${{ github.ref_name }}" >> "$GITHUB_ENV"
      - name: Generate
        run: |
           ./generate.sh "${{ matrix.libcint_ref }}" "${{ env.REF }}"
      - name: Test archive (GCC)
        run: |
            export CC=gcc
            ./tests.sh
      - name: Test archive (Clang)
        run: |
            export CC=clang
            ./tests.sh
      - name: Upload archive
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libcint/libcint.tar.gz
          asset_name: libcint_${{ matrix.libcint_ref }}.tar.gz
          tag: ${{ env.REF }}
          overwrite: true
      - name: Upload wrap
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libcint/libcint.wrap
          asset_name: libcint_${{ matrix.libcint_ref }}.wrap
          tag: ${{ env.REF }}
          overwrite: true
