name: Publish patched code

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Patch and publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        libcint_ref: ['v6.1.2']
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get -y install clisp
      - name: Fetch & Generate
        run: |
           # clone and checkout
           git clone https://github.com/sunqm/libcint.git
           cd libcint/
           git checkout ${{ matrix.libcint_ref }}
           # generate
           ../patch.sh
           # create archive
           tar -czf libcint.tar.gz src/ include/ meson.build meson_options.txt
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libcint/libcint.tar.gz
          asset_name: libcint_${{ matrix.libcint_ref }}.tar.gz
          tag: latest
          overwrite: true
